version: '3.8'

services:
  # Application Node.js pour production
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-api-prod
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      # Utilise MongoDB Atlas en production
      - DATABASE_URL=${DATABASE_URL}
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - todo-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx comme reverse proxy (optionnel)
  nginx:
    image: nginx:alpine
    container_name: todo-api-nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge